name: å®šæ—¶åŒæ­¥ Gitee ä»“åº“

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions:
  contents: write   # âœ… å…³é”®ï¼šå…è®¸æ¨é€ä»£ç 


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Clone Gitee repo(s)
        run: |
          rm -rf repos
          mkdir repos
          cd repos
          git clone --depth=1 https://linganmin:cdf832312f130e2125157f802e357a9d@gitee.com/harmonyos_samples/VideoCast.git &
          git clone --depth=1 https://linganmin:cdf832312f130e2125157f802e357a9d@gitee.com/harmonyos_samples/audio-interaction.git &

          wait
      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # éå†æ¯ä¸ªå­ç›®å½•
          for dir in repos/*; do
            echo "Processing $dir"
            # æ‹‰å– LFS å¯¹è±¡
            if [ -f "$dir/.gitattributes" ]; then
              cd "$dir"
              git lfs pull || echo "No LFS objects for $dir"
              cd ..
            fi
            # åˆ é™¤å­ç›®å½•çš„ .git
            if [ -d "$dir/.git" ]; then
              rm -rf "$dir/.git"
            fi
            # ç§»åŠ¨å†…å®¹åˆ° GitHub ä»“åº“æ ¹ç›®å½•
            if [ -d "$dir" ]; then
              mv "$dir" ./
            fi
          done
          rm -rf repos                   # æ¸…ç†ä¸´æ—¶ç›®å½•
          git add .
          git commit -m "ğŸ”„ Auto sync from Gitee on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
