name: å®šæ—¶åŒæ­¥ Gitee ä»“åº“

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions:
  contents: write   # âœ… å…³é”®ï¼šå…è®¸æ¨é€ä»£ç 


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Clone Gitee repo(s)
        run: |
          git clone --depth=1 https://linganmin:cdf832312f130e2125157f802e357a9d@gitee.com/harmonyos_samples/text-effects.git

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ğŸ”„ Auto sync from Gitee on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
